var searchData=
[
  ['valid_3081',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()']]],
  ['value_3082',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()']]],
  ['value_5fcomp_3083',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5for_3084',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['vector_3085',['vector',['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector']]],
  ['vfprintf_3086',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_3087',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_3088',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_3089',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vprintf_3090',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_3091',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_3092',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_3093',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_3094',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_3095',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_3096',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_3097',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_3098',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
