var searchData=
[
  ['va_5flist_3001',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_3002',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid_3003',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()']]],
  ['validate_5fenclave_5fname_2eh_3004',['validate_enclave_name.h',['http://docs.ros2.org/galactic/api/rcl/validate__enclave__name_8h.html.html',1,'']]],
  ['validate_5ffull_5ftopic_5fname_2eh_3005',['validate_full_topic_name.h',['http://docs.ros2.org/galactic/api/rmw/validate__full__topic__name_8h.html.html',1,'']]],
  ['validate_5fnamespace_2eh_3006',['validate_namespace.h',['http://docs.ros2.org/galactic/api/rmw/validate__namespace_8h.html.html',1,'']]],
  ['validate_5fnode_5fname_2eh_3007',['validate_node_name.h',['http://docs.ros2.org/galactic/api/rmw/validate__node__name_8h.html.html',1,'']]],
  ['validate_5ftopic_5fname_2eh_3008',['validate_topic_name.h',['http://docs.ros2.org/galactic/api/rcl/validate__topic__name_8h.html.html',1,'']]],
  ['value_3009',['value',['../structrclcpp_1_1node__interfaces_1_1ParameterInfo.html#aca2a24368f71199fee9af5371f95e2a0',1,'rclcpp::node_interfaces::ParameterInfo::value()'],['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()']]],
  ['value_20_3e_3e_3010',['value &gt;&gt;',['../structrclcpp_1_1detail_1_1SubscriptionCallbackTypeHelper_3_01MessageT_00_01CallbackT_00_01typena1a54c8a1da7db436425a00ee55c1782c.html',1,'rclcpp::detail::value &gt;&gt;&lt; MessageT, CallbackT &gt;'],['../structrclcpp_1_1detail_1_1SubscriptionCallbackTypeHelper_3_01MessageT_00_01CallbackT_00_01typena60b5d887c4ac0d9e6f44e8e305e7bbe9.html',1,'rclcpp::detail::value &gt;&gt;&lt; MessageT, CallbackT &gt;'],['../structrclcpp_1_1detail_1_1SubscriptionCallbackTypeHelper_3_01MessageT_00_01CallbackT_00_01typenadc4bf3dd18d9b06fb4953d418cce56f4.html',1,'rclcpp::detail::value &gt;&gt;&lt; MessageT, CallbackT &gt;'],['../structrclcpp_1_1detail_1_1SubscriptionCallbackTypeHelper_3_01MessageT_00_01CallbackT_00_01typena9d27432b3f92c0d1667982c81da8c360.html',1,'rclcpp::detail::value &gt;&gt;&lt; MessageT, CallbackT &gt;'],['../structrclcpp_1_1detail_1_1SubscriptionCallbackTypeHelper_3_01MessageT_00_01CallbackT_00_01typena63c46c80c4f19eb6c17de5b8ab32c78b.html',1,'rclcpp::detail::value &gt;&gt;&lt; MessageT, CallbackT &gt;'],['../structrclcpp_1_1detail_1_1SubscriptionCallbackTypeHelper_3_01MessageT_00_01CallbackT_00_01typena354c982515e9e169abe2177039ab87da.html',1,'rclcpp::detail::value &gt;&gt;&lt; MessageT, CallbackT &gt;']]],
  ['value_5fcomp_3011',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5fcompare_3012',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map::value_compare']]],
  ['value_5for_3013',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['value_5fto_5fstring_3014',['value_to_string',['../classrclcpp_1_1Parameter.html#aaf2dc3ad81432a965443129abd370415',1,'rclcpp::Parameter']]],
  ['variant_5ftype_3015',['variant_type',['../structrclcpp_1_1detail_1_1AnySubscriptionCallbackHelper.html#a15a88e8e217205cb58b8b8388fff31ae',1,'rclcpp::detail::AnySubscriptionCallbackHelper']]],
  ['vector_3016',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['vector_3c_20buffert_20_3e_3017',['vector&lt; BufferT &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20const_20rcl_5fguard_5fcondition_5ft_20_2a_20_3e_3018',['vector&lt; const rcl_guard_condition_t * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20qospolicykind_20_3e_3019',['vector&lt; QosPolicyKind &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3acallbackgroup_3a_3aweakptr_20_3e_3020',['vector&lt; rclcpp::CallbackGroup::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3aclientbase_3a_3asharedptr_20_3e_3021',['vector&lt; rclcpp::ClientBase::SharedPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3aclientbase_3a_3aweakptr_20_3e_3022',['vector&lt; rclcpp::ClientBase::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3aclock_3a_3asharedptr_20_3e_3023',['vector&lt; rclcpp::Clock::SharedPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3aevent_3a_3aweakptr_20_3e_3024',['vector&lt; rclcpp::Event::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3anode_5finterfaces_3a_3anodegraphinterface_20_2a_20_3e_3025',['vector&lt; rclcpp::node_interfaces::NodeGraphInterface * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3aparameter_20_3e_3026',['vector&lt; rclcpp::Parameter &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3aservicebase_3a_3asharedptr_20_3e_3027',['vector&lt; rclcpp::ServiceBase::SharedPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3aservicebase_3a_3aweakptr_20_3e_3028',['vector&lt; rclcpp::ServiceBase::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3asubscriptionbase_3a_3asharedptr_20_3e_3029',['vector&lt; rclcpp::SubscriptionBase::SharedPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3asubscriptionbase_3a_3aweakptr_20_3e_3030',['vector&lt; rclcpp::SubscriptionBase::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3atimerbase_3a_3asharedptr_20_3e_3031',['vector&lt; rclcpp::TimerBase::SharedPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3atimerbase_3a_3aweakptr_20_3e_3032',['vector&lt; rclcpp::TimerBase::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3awaitable_3a_3asharedptr_20_3e_3033',['vector&lt; rclcpp::Waitable::SharedPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3awaitable_3a_3aweakptr_20_3e_3034',['vector&lt; rclcpp::Waitable::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_20_3e_3035',['vector&lt; std::pair &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20const_20rcl_5fclient_5ft_20_3e_20_3e_3036',['vector&lt; std::shared_ptr&lt; const rcl_client_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20const_20rcl_5fservice_5ft_20_3e_20_3e_3037',['vector&lt; std::shared_ptr&lt; const rcl_service_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20const_20rcl_5fsubscription_5ft_20_3e_20_3e_3038',['vector&lt; std::shared_ptr&lt; const rcl_subscription_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20const_20rcl_5ftimer_5ft_20_3e_20_3e_3039',['vector&lt; std::shared_ptr&lt; const rcl_timer_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20rclcpp_3a_3aclientbase_20_3e_20_3e_3040',['vector&lt; std::shared_ptr&lt; rclcpp::ClientBase &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20rclcpp_3a_3aguardcondition_20_3e_20_3e_3041',['vector&lt; std::shared_ptr&lt; rclcpp::GuardCondition &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20rclcpp_3a_3aqoseventhandlerbase_20_3e_20_3e_3042',['vector&lt; std::shared_ptr&lt; rclcpp::QOSEventHandlerBase &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20rclcpp_3a_3aservicebase_20_3e_20_3e_3043',['vector&lt; std::shared_ptr&lt; rclcpp::ServiceBase &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20rclcpp_3a_3atimerbase_20_3e_20_3e_3044',['vector&lt; std::shared_ptr&lt; rclcpp::TimerBase &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20rclcpp_3a_3awaitable_20_3e_20_3e_3045',['vector&lt; std::shared_ptr&lt; rclcpp::Waitable &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e_3046',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20topicstatscollector_20_3e_20_3e_3047',['vector&lt; std::unique_ptr&lt; TopicStatsCollector &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aweak_5fptr_3c_20rclcpp_3a_3aclientbase_20_3e_20_3e_3048',['vector&lt; std::weak_ptr&lt; rclcpp::ClientBase &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aweak_5fptr_3c_20rclcpp_3a_3aguardcondition_20_3e_20_3e_3049',['vector&lt; std::weak_ptr&lt; rclcpp::GuardCondition &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aweak_5fptr_3c_20rclcpp_3a_3aservicebase_20_3e_20_3e_3050',['vector&lt; std::weak_ptr&lt; rclcpp::ServiceBase &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aweak_5fptr_3c_20rclcpp_3a_3atimerbase_20_3e_20_3e_3051',['vector&lt; std::weak_ptr&lt; rclcpp::TimerBase &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20subscriptionentry_20_3e_3052',['vector&lt; SubscriptionEntry &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20uint64_5ft_20_3e_3053',['vector&lt; uint64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20waitableentry_20_3e_3054',['vector&lt; WaitableEntry &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20weaksubscriptionentry_20_3e_3055',['vector&lt; WeakSubscriptionEntry &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20weakwaitableentry_20_3e_3056',['vector&lt; WeakWaitableEntry &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vfprintf_3057',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_3058',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_3059',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_3060',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['visibility_5fcontrol_2eh_3061',['visibility_control.h',['http://docs.ros2.org/galactic/api/rmw/visibility__control_8h.html.html',1,'(Global Namespace)'],['http://docs.ros2.org/galactic/api/rcutils/visibility__control_8h.html.html',1,'(Global Namespace)']]],
  ['visibility_5fcontrol_2ehpp_3062',['visibility_control.hpp',['../visibility__control_8hpp.html',1,'']]],
  ['visibility_5fcontrol_5fmacros_2eh_3063',['visibility_control_macros.h',['http://docs.ros2.org/galactic/api/rcutils/visibility__control__macros_8h.html.html',1,'']]],
  ['voidalloc_3064',['VoidAlloc',['../classrclcpp_1_1memory__strategies_1_1allocator__memory__strategy_1_1AllocatorMemoryStrategy.html#aecb9b437636999fd7a8927121ebe3c9e',1,'rclcpp::memory_strategies::allocator_memory_strategy::AllocatorMemoryStrategy']]],
  ['voidalloctraits_3065',['VoidAllocTraits',['../classrclcpp_1_1memory__strategies_1_1allocator__memory__strategy_1_1AllocatorMemoryStrategy.html#a5d35276dd5cbdb9cef1f7504119879e9',1,'rclcpp::memory_strategies::allocator_memory_strategy::AllocatorMemoryStrategy']]],
  ['voidcallbacktype_3066',['VoidCallbackType',['../namespacerclcpp.html#aba01c682b9c93b3ff844cc36ea80fda1',1,'rclcpp']]],
  ['volatile_3067',['Volatile',['../namespacerclcpp.html#a13741e50907b01ddeea83a16188edf0aa3e3af98b6b48c7e593d8d18863e3333b',1,'rclcpp']]],
  ['vprintf_3068',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_3069',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_3070',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_3071',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_3072',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_3073',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_3074',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_3075',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_3076',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
