var searchData=
[
  ['va_5flist',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()']]],
  ['validate_5ffull_5ftopic_5fname_2eh',['validate_full_topic_name.h',['http://docs.ros2.org/crystal/api/rmw/validate__full__topic__name_8h.html',1,'']]],
  ['validate_5fnamespace_2eh',['validate_namespace.h',['http://docs.ros2.org/crystal/api/rmw/validate__namespace_8h.html',1,'']]],
  ['validate_5fnode_5fname_2eh',['validate_node_name.h',['http://docs.ros2.org/crystal/api/rmw/validate__node__name_8h.html',1,'']]],
  ['validate_5ftopic_5fname_2eh',['validate_topic_name.h',['http://docs.ros2.org/crystal/api/rcl/validate__topic__name_8h.html',1,'']]],
  ['value',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()']]],
  ['value_5fcomp',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap::value_compare']]],
  ['value_5for',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['value_5fto_5fstring',['value_to_string',['http://docs.ros2.org/crystal/api/rclcpp/classrclcpp_1_1Parameter.html#aaf2dc3ad81432a965443129abd370415',1,'rclcpp::Parameter']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['vector_3c_20rclcpp_3a_3aclientbase_3a_3aweakptr_20_3e',['vector&lt; rclcpp::ClientBase::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3aservicebase_3a_3aweakptr_20_3e',['vector&lt; rclcpp::ServiceBase::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3asubscriptionbase_3a_3aweakptr_20_3e',['vector&lt; rclcpp::SubscriptionBase::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3atimerbase_3a_3aweakptr_20_3e',['vector&lt; rclcpp::TimerBase::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rclcpp_3a_3awaitable_3a_3aweakptr_20_3e',['vector&lt; rclcpp::Waitable::WeakPtr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vfprintf',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['visibility_5fcontrol_2eh',['visibility_control.h',['http://docs.ros2.org/crystal/api/rcl_action/visibility__control_8h.html',1,'(Global Namespace)'],['http://docs.ros2.org/crystal/api/rcl/visibility__control_8h.html',1,'(Global Namespace)'],['http://docs.ros2.org/crystal/api/rmw/visibility__control_8h.html',1,'(Global Namespace)'],['http://docs.ros2.org/crystal/api/rcutils/visibility__control_8h.html',1,'(Global Namespace)']]],
  ['visibility_5fcontrol_2ehpp',['visibility_control.hpp',['../visibility__control_8hpp.html',1,'(Global Namespace)'],['http://docs.ros2.org/crystal/api/rclcpp/visibility__control_8hpp.html',1,'(Global Namespace)']]],
  ['voidalloc',['VoidAlloc',['http://docs.ros2.org/crystal/api/rclcpp/classrclcpp_1_1memory__strategies_1_1allocator__memory__strategy_1_1AllocatorMemoryStrategy.html#aecb9b437636999fd7a8927121ebe3c9e',1,'rclcpp::memory_strategies::allocator_memory_strategy::AllocatorMemoryStrategy']]],
  ['voidalloctraits',['VoidAllocTraits',['http://docs.ros2.org/crystal/api/rclcpp/classrclcpp_1_1memory__strategies_1_1allocator__memory__strategy_1_1AllocatorMemoryStrategy.html#a5d35276dd5cbdb9cef1f7504119879e9',1,'rclcpp::memory_strategies::allocator_memory_strategy::AllocatorMemoryStrategy']]],
  ['voidcallbacktype',['VoidCallbackType',['http://docs.ros2.org/crystal/api/rclcpp/namespacerclcpp.html#aba01c682b9c93b3ff844cc36ea80fda1',1,'rclcpp']]],
  ['vprintf',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
