name: CI

on:
  push:
    branches: [ doc_gen ]
  pull_request:
    branches: [ doc_gen ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            rosdistro: dashing
          - os: ubuntu-18.04
            rosdistro: eloquent
          - os: ubuntu-20.04
            rosdistro: foxy
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.23
      with:
        required-ros-distributions: ${{ matrix.rosdistro }}
    - name: Install dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y curl doxygen python3-pip
        pip3 install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
    - name: Build code and docs
      run: |
        export PATH="/home/runner/.local/bin:$PATH"
        ${GITHUB_WORKSPACE}/build_docs.sh -y -r ${{ matrix.rosdistro }}
